# Generated by Django 4.1 on 2022-09-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsocial', '0003_relationship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
